### ISSUE TITLE
The troubleshooting link in the Readme is broken

### ISSUE THREAD

**Issue by hnez** [linux-automation/lxa-iobus#19]
The TROUBLESHOOTING.rst file is no longer present in the repo.
We should remove the reference to it and replace it with a link to this URL:

- `https://lxa-iobus.readthedocs.io/en/latest/troubleshooting.html`

**Comment by SmithChart** [comment]
There was a ``ref`` left as _copy-and-pasta_ error from the synchronization with the documentation. I have fixed this in https://github.com/linux-automation/lxa-iobus/commit/4c9a59df086d23df7a9a5c7c3a78ed8c6ef12f99 . This was needed for the pypi-release anyway. Does this fix your issue?

Currently there are no ref to  ``TROUBLESHOOTING.rst`` left.

**Comment by hnez** [comment]
Oh, you are right about it not being a reference to ` TROUBLESHOOTING.rst`, I did not actually look into it that much.
The mentioned commit fixes it for me.
Will close the issue now, thx
