### ISSUE TITLE
Add support for SERVER_TIMEOUT SDO

### ISSUE THREAD

**Issue by hnez** [linux-automation/lxa-iobus#20]
There is a new SDO endpoint `SERVER_TIMEOUT_SDO` (`0x2d06`) that, when set to `1` enables a watchdog mode in the node firmware.
When enabled the node will reset its `node_id` after not being pinged for some time, so that it can be re-discovered via LSS.

I would go about implementing this feature like this:

- Break out the discovery of supported `SDO`s from `LxaNode::get_info()` into a separate method (maybe also cache the results)
- Check the supported `SDO`s early in the node discovery
- Enable `SERVER_TIMEOUT` for nodes that support it as early in the node discovery as possible

**Comment by SmithChart** [comment]
During firmware development we have decided that the watchdog should default to always on.  So we do not need to change any behavior in the server component.

I will add the watchdog-diable to the _commandline-use_ documentation for the products. I'll leave this issue open to track that change.

**Comment by hnez** [comment]
It looks to me like the documentation changes are now online.
I will close this issue now.
