### ISSUE TITLE
Locator should time out

### ISSUE THREAD

**Issue by Bastian-Krause** [linux-automation/lxa-iobus#35]
LXAIOBus nodes tend to be left in "locate" mode making it impossible to locate a new node. The locator function must be turned off manually, either via the web interface or with the button on the LXAIOBus. Only after that, the locator mode is useful.

When activating the locator mode on a node, it should time out after a few minutes (10? 30?).

**Comment by SmithChart** [comment]
Hi @Bastian-Krause,
the latest firmware release `0.6.0` that has been merged with #41 now has a 30 minute timeout for the locator. 

I'll close this issue for now. Feel free to open again if we have missed anything.
